version: '3.7'
services:
  ws-ban-ip:
    image: kfroman/ws-ban-ip:0.0.1.RELEASE
    ports:
      - "8001:8001"
    restart: always
    networks:
      - evaluate-compose-network

  ws-info-ip:
    image: kfroman/ws-info-ip:0.0.1.RELEASE
    ports:
      - "8000:8000"
    restart: always
    environment:
      WS_BLACK_LIST: http://ws-ban-ip
    depends_on:
      - ws-ban-ip
    networks:
      - evaluate-compose-network
  
# Networks to be created to facilitate communication between containers
networks:
  evaluate-compose-network: