version: '3.7'
services:
  evaluacion-ip:
    image: kfroman/evaluacion-ip:0.0.1.RELEASE
    ports:
      - "8001:8001"
    restart: always
    networks:
      - evaluate-compose-network

  evaluacion-fraude:
    image: kfroman/evaluacion-fraude:0.0.1.RELEASE
    ports:
      - "8000:8000"
    restart: always
    environment:
      CURRENCY_EXCHANGE_SERVICE_HOST: http://evaluacion-ip
    depends_on:
      - evaluacion-ip
    networks:
      - evaluate-compose-network
  
# Networks to be created to facilitate communication between containers
networks:
  evaluate-compose-network: