FROM maven:3.6.3-jdk-8-slim AS build
WORKDIR /home/app
COPY . /home/app

#Variables
#WS_BLACK_LIST=http://ws-info-ip
#WS_COUNTRY=https://api.ip2country.info/
#WS_CURRENCY=https://restcountries.eu/rest/v2/
#WS_CONVERSION=http://data.fixer.io/api/

RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8000
COPY --from=build /home/app/target/*.jar app.jar
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]